# Generated by Django 5.0.7 on 2024-07-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_columna', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='calidad_producto.archivo')),
            ],
        ),
    ]
