# Generated by Django 5.0.7 on 2024-07-30 16:15

import calidad_producto.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('voltaje_a', models.CharField(max_length=50)),
                ('voltaje_b', models.CharField(max_length=50)),
                ('voltaje_c', models.CharField(blank=True, max_length=50, null=True)),
                ('flicker_a', models.CharField(max_length=50)),
                ('flicker_b', models.CharField(max_length=50)),
                ('flicker_c', models.CharField(blank=True, max_length=50, null=True)),
                ('vthd_a', models.CharField(max_length=50)),
                ('vthd_b', models.CharField(max_length=50)),
                ('vthd_c', models.CharField(blank=True, max_length=50, null=True)),
                ('desbalance', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=calidad_producto.models.cargar_a)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('informacion', models.JSONField(default=dict)),
                ('analizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad_producto.analizador')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad_producto.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad_producto.tipo')),
            ],
        ),
    ]
