# Generated by Django 5.0.7 on 2024-07-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_producto', '0002_remove_archivoinfo_nombre_columna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoinfo',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='calidad_producto.archivo'),
        ),
    ]
