# Generated by Django 5.0.7 on 2024-07-24 19:54

import calidad_producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_producto', '0003_alter_archivoinfo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='categoria',
            field=models.CharField(choices=[('armonicos', 'Armonicos'), ('tendencias', 'Tendencias'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=calidad_producto.models.cargar_a),
        ),
    ]
